### ISSUE TITLE
SDK 32 or above cannot asking permission turn on bluetooth.

### ISSUE THREAD

**Issue by LimSieKuang** [CesarBalzer/Cordova-Plugin-BTPrinter#73]
hello, i have download demo app and try works fine.. but when i tried open in my android studio sdk and rebuild app not works for sdk 32 or above.. device can't asking a turn on bluetooth.. can you help me?

**Comment by nandhawalrost** [comment]
i was having the same issue and i've fixed it. i rewrite the plugin, try my version: https://github.com/nandhawalrost/Cordova-Plugin-BTPrinter

**Comment by LimSieKuang** [comment]
> i was having the same issue and i've fixed it. i rewrite the plugin, try my version: https://github.com/nandhawalrost/Cordova-Plugin-BTPrinter

this is compatible for SDK 32 or above?

**Comment by nandhawalrost** [comment]
> > i was having the same issue and i've fixed it. i rewrite the plugin, try my version: https://github.com/nandhawalrost/Cordova-Plugin-BTPrinter
> 
> this is compatible for SDK 32 or above?

yes it is.

**Comment by LimSieKuang** [comment]
> > > i was having the same issue and i've fixed it. i rewrite the plugin, try my version: https://github.com/nandhawalrost/Cordova-Plugin-BTPrinter
> > 
> > 
> > this is compatible for SDK 32 or above?
> 
> yes it is.

hello sir, still not display popup turn on the bluetooth devices.

**Comment by LimSieKuang** [comment]
> > > i was having the same issue and i've fixed it. i rewrite the plugin, try my version: https://github.com/nandhawalrost/Cordova-Plugin-BTPrinter
> > 
> > 
> > this is compatible for SDK 32 or above?
> 
> yes it is.

i have error :

Permission Denial: starting Intent { act=android.bluetooth.adapter.action.REQUEST_ENABLE cmp=com.android.settings/.bluetooth.RequestPermissionActivity } on android 13.

**Comment by kenfouo** [comment]
try my fork of the Cordova-Plugin-Bluetooth-Printer
cordova plugin add https://github.com/kenfouo/Cordova-Plugin-Bluetooth-Printer.git

For Android 12, also use this script to request nearby device permissions:

 try {   
    var permissions = cordova.plugins.permissions;
    var bluetoothPermissions = [
        permissions.BLUETOOTH,
        permissions.BLUETOOTH_ADMIN,
        permissions.BLUETOOTH_SCAN,
        permissions.BLUETOOTH_CONNECT,
        permissions.ACCESS_FINE_LOCATION // Nécessaire pour le scan Bluetooth
    ];
    
    // Vérifier les permissions
    permissions.hasPermission(bluetoothPermissions, function(status) {
        if (!status.hasPermission) {
            // Demander les permissions
            permissions.requestPermissions(bluetoothPermissions, function(status) {
                if (status.hasPermission) {
                    console.log('Permissions accordées pour accéder aux appareils à proximité.');
                } else {
                    alert('Permissions refusées pour accéder aux appareils à proximité.');
                }
            }, function(error) {
                alert('Erreur lors de la demande de permissions: ' + JSON.stringify(error));
            });
        } else {
            console.log('Permissions déjà accordées pour accéder aux appareils à proximité.');              
        }                                                                        
    }, function(error) {
        alert('Erreur lors de la vérification des permissions: ' + JSON.stringify(error));
    });

} catch (error) {                                                        
    alert('error '+error);                                                         
}  
this code uses the plugin:
https://github.com/NeoLSN/cordova-plugin-android-permissions
